name: image-processing-system

services:
  orchestrator:
    build:
      context: .
      args:
        MODE: development
    environment:
      MODE: development
      BASE_URL: http://localhost:8000
      LOGS_ROOT: /var/log/orchestrator/
      STATIC_ROOT: /var/www/orchestrator/static/
      MEDIA_ROOT: /var/www/orchestrator/media/
    env_file:
    - ./envs/postgres.env
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000

  postgres:
    env_file:
      - ./envs/postgres.env
